melspec_config:
  n_mels: 128
  sample_rate: 44100
  win_length: 1024
  hop_length: 512
  n_fft: 2048
  fmin: 40
  fmax: 32000
  clamp: 0.00001

hubert_config:
  combine_mel: False
  # hubertsoft:   xxx.pt      hid_dim: 256
  # cnhubert:     xxx_folder  hid_dim: 768
  # whisper-ppg:  xxx.pt      hid_dim: 1024
  encoder: 'cnhubert'
  model_path: "dependencies/cnhubert"
  sample_rate: 16000
  hop_size: 320
  hidden_dims: 768

# 只检测data文件夹下，"full_label"、"weak_label"、"no_label"文件夹内数据
data_folder: data/
binary_folder: data/binary_base

valid_set_size: 15
valid_sets:
  - 000_buweixia_1
  - 000_buweixia_2
  - 000_buweixia_3
  - 013_mingtianhuigenghao_1
  - 013_mingtianhuigenghao_2
  - 013_mingtianhuigenghao_3
  - 036_zuiqiannian_1
  - 036_zuiqiannian_2
  - 036_zuiqiannian_3
valid_set_preferred_folders:
  - test
ignored_phonemes:
  - AP
  - SP
  - EP
  - GS
  - <AP>
  - <SP>
  - ''
  - pau
  - cl

# Mandatory marking as vowel
vowel_phonemes:
  - y
  - w

# Two-part dictionary used to determine vowels
dictionary_paths:
  - dictionary/opencpop-extension.txt
max_length: 45 # unit: second



