hubert_config:
  # hubertsoft:     xxx.pt      hid_dim: 256
  # cnhubert:       xxx_folder  hid_dim: 768    推荐
  # cnhubert-large: xxx_folder  hid_dim: 1024
  # whisper-ppg:    xxx.pt      hid_dim: 1024
  encoder: cnhubert
  model_path: dependencies/cnhubert
  sample_rate: 16000
  hop_size: 320
  channel: 768

# 只检测data文件夹下，"full_label"、"weak_label"、"no_label"文件夹内数据
data_folder: data/
binary_folder: data/binary_base

# 路径为{datafolder}/evaluate，可留空，此时evaluate_loss不生效
# 临时格式为：evaluate_folder/spk/wavs/xxx.wav && xxx.lab、evaluate_folder/spk/TextGrid/xxx.TextGrid
# TextGrid建议使用人工修正后的文件作为标定，仅包含"SP"和模型训练集中出现过的音素
evaluate_dictionary: dictionary/opencpop-extension.txt

valid_set_size: 15
valid_sets:
  - 000_buweixia_1
  - 000_buweixia_2
  - 000_buweixia_3
  - 013_mingtianhuigenghao_1
  - 013_mingtianhuigenghao_2
  - 013_mingtianhuigenghao_3
  - 036_zuiqiannian_1
  - 036_zuiqiannian_2
  - 036_zuiqiannian_3
# valid_sets: [] 时，按valid_set_size数量随机抽取
valid_sets: []
valid_set_preferred_folders:
  - test
ignored_phonemes:
  - AP
  - SP
  - EP
  - GS
  - <AP>
  - <SP>
  - ''
  - pau
  - cl

# Mandatory marking as vowel
vowel_phonemes:
  - y
  - w

# Two-part dictionary used to determine vowels
dictionary_paths:
  - dictionary/opencpop-extension.txt
max_length: 45 # unit: second


melspec_config:
  n_mels: 128
  sample_rate: 44100
  win_length: 1024
  hop_length: 512
  n_fft: 2048
  fmin: 40
  fmax: 16000
  clamp: 0.00001