datasets_config: configs/datasets_config.yaml

data_folder: data/
binary_folder: data/binary_base

# valid_set_size大于0时，按数量随机抽取、否则使用datasets内的验证集
valid_set_size: 0
max_length: 45 # 单条音频最大时长

# hubertsoft:     model_path: xxx.pt      hid_dim: 256
# cnhubert:       model_path: xxx_folder  hid_dim: 768    推荐
# cnhubert-large: model_path: xxx_folder  hid_dim: 1024
# whisper-ppg:    model_path: xxx.pt      hid_dim: 1024
hubert_config:
  encoder: cnhubert
  model_path: dependencies/cnhubert
  sample_rate: 16000
  hop_size: 320
  channel: 768

melspec_config:
  n_mels: 128
  sample_rate: 44100
  win_length: 1024
  hop_length: 512
  n_fft: 2048
  fmin: 40
  fmax: 16000
  clamp: 0.00001
