melspec_config:
  n_mels: 128
  sample_rate: 44100
  win_length: 1024
  hop_length: 512
  n_fft: 2048
  fmin: 40
  fmax: 32000
  clamp: 0.00001
  scale_factor: 4

data_folder: data/
binary_folder: data/binary_base

valid_set_size: 15
valid_set_preferred_folders:
  - test
ignored_phonemes:
  - AP
  - SP
  - EP
  - GS
  - <AP>
  - <SP>
  - ''
  - pau
  - cl

# Mandatory marking as vowel
vowel_phonemes:
  - y
  - w

# Two-part dictionary used to determine vowels
dictionary_paths:
  - dictionary/opencpop-extension.txt
max_length: 45 # unit: second

hubert_config:
  combine_mel: False
  encoder: 'hubertsoft'
  model_path: "dependencies/hubert/hubert-soft-35d9f29f.pt"
  sample_rate: 16000
  hop_size: 320
  hidden_dims: 256
  layer: 12  # 使用的特征层

